config/routes.rb
Rails.application.routes.draw do


  # 顧客用
# URL /customers/sign_in ...
devise_for :customers, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}

scope module: :public do
  root to: 'homes#top'
  get 'homes/about', as: 'about'
  get '/customers/:id/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
  patch '/customers/:id/withdraw' => 'customers#withdraw', as: 'withdraw'
  resources :items, only: [:index, :show]
  resources :customers, only: [:show, :edit, :update]
  resources :cart_items, only: [:index, :update, :destroy, :destroy_all, :create]
  resources :orders, only: [:new, :comfirm, :complete, :create, :index, :show]
  resources :addresses, only: [:index, :edit, :create, :update, :destroy]
end

namespace :admin do
  root to: 'homes#top'
  resources :items, only: [:index, :new, :create, :show, :edit, :update]
  resources :genres, only: [:index, :create, :edit, :update]
  resources :customers, only: [:index, :show, :edit, :update]
  resources :admins, only: [:destroy]
  resources :orders, only: [:show]
end




  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def full_name
    self.last_name + " " + self.first_name
  end

end

app/models/item.rb
class Item < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
end

app/controllers/admin/admins_controller.rb
class Admin::AdminsController < ApplicationController
  before_action :authenticate_customer!
  
  
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!
  layout 'admin'
  
  def index
  end
  
  def edit
  end
  
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  layout 'admin'
  
  def top
  end
    
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!


  def index
    @admin_item = Item.all
  end

  def new
    @admin_item = Item.new
  end

  def create
    @admin_item = Item.new
    if @admin_item.save
      redirect_to admin_item_path(@item.id)
    else
      flash.now[:notice] = "error"
      @items = Items.all
      render :index
    end
  end

  def show
  end

  def edit
  end


  private

  def item_params
    params.require(:item).permit(:name, :image, :introduction, :price)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/helpers/admin/admins_helper.rb
module Admin::AdminsHelper
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Admin - Nagano Cake</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
  <% if admin_signed_in? %>
    　<li>
        <%= link_to "商品一覧", admin_items_path %>
      </li>
      <li>
        <%= link_to "会員一覧",  admin_customers_path %>
      </li>
      <li>
        <%= link_to "注文履歴一覧", admin_items_path %>
    　</li>

    　<div class="text-right">

      　<%= link_to 'ログアウト', destroy_admin_session_path, method: :delete %>
    　</div>

    <% else %>
      <li>
        <%= link_to "About", about_path %>
      </li>
      <li>
        <%= link_to "商品一覧", admin_items_path %>
      </li>
      <li>
        <%= link_to "新規登録", new_admin_item_path %>
      </li>
      <li>
        <%= link_to "ログイン", new_admin_session_path %>
      </li>
  <% end %>
  <%= yield %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
    <% if customer_signed_in? %>
    　<li>
        <%= link_to "マイページ", customer_path(current_customer) %>
      </li>
      <li>
        <%= link_to "商品一覧", items_path %>
      </li>
      <li>
        <%= link_to "カート", cart_items_path(current_customer) %>
      </li>
      <li>
        <%= link_to "ログアウト", destroy_customer_session_path, method: :delete %>
      </li>
    <% else %>
      <li>
        <%= link_to "About", about_path %>
      </li>
      <li>
        <%= link_to "商品一覧", items_path %>
      </li>
      <li>
        <%= link_to "新規登録", new_customer_registration_path %>
      </li>
      <li>
        <%= link_to "ログイン", new_customer_session_path %>
      </li>
    <% end %>
  </header>

    <%= yield %>
  </body>
</html>